export const divisionData = [
  "Secretary",
  "CTO",
  "Technical Lead",
  "Front End Dev",
  "Back End Dev",
  "Mobile Dev",
  "Technical Architecture",
  "System Analyst",
  "DevOps",
  "Product Manager",
  "UI/UX",
  "SCRUM Master",
  "Principal Software Engineer",
  "RnD Developer",
  "Security Developer",
  "Lead 1",
  "Co-Lead 2",
  "Staff",
  "LEAD",
]
